import mongoose from "mongoose";

/**
 * MoodStats.model.js
 *
 * Persists the computed mood statistics snapshot for a help seeker.
 * Generated by moodStats.service.js and consumed by the help-provider dashboard.
 *
 * One record per user — always overwritten on recompute (upsert pattern).
 */

// ─── Sub-schemas ──────────────────────────────────────────────────────────────

const EmotionBreakdownItemSchema = new mongoose.Schema(
  {
    emotion:    { type: String, required: true, trim: true },
    count:      { type: Number, required: true, min: 0 },
    percentage: { type: Number, required: true, min: 0, max: 100 },
    /** Weighted average confidence score (0–1) for this emotion label */
    avgScore:   { type: Number, required: true, min: 0, max: 1 },
  },
  { _id: false }
);

const PolarityBucketSchema = new mongoose.Schema(
  {
    count:      { type: Number, required: true, min: 0 },
    percentage: { type: Number, required: true, min: 0, max: 100 },
  },
  { _id: false }
);

const DailyTrendEntrySchema = new mongoose.Schema(
  {
    /** ISO date string "YYYY-MM-DD" */
    date:     { type: String, required: true },
    /** Polarity that dominated this calendar day */
    dominant: { type: String, enum: ["positive", "negative", "neutral"], required: true },
    /** Percentage of posts with positive polarity that day */
    positive: { type: Number, required: true, min: 0, max: 100 },
    /** Percentage of posts with negative polarity that day */
    negative: { type: Number, required: true, min: 0, max: 100 },
    /** Percentage of posts with neutral polarity that day */
    neutral:  { type: Number, required: true, min: 0, max: 100 },
  },
  { _id: false }
);

const VolatilitySchema = new mongoose.Schema(
  {
    /** Ratio of day-to-day mood shifts to total days (0–1) */
    score: { type: Number, required: true, min: 0, max: 1 },
    /** Human-readable bucket: "low" | "moderate" | "high" */
    label: { type: String, enum: ["low", "moderate", "high"], required: true },
  },
  { _id: false }
);

const WeekSnapshotSchema = new mongoose.Schema(
  {
    totalPosts:         { type: Number, required: true, min: 0 },
    positivePercentage: { type: Number, required: true, min: 0, max: 100 },
    negativePercentage: { type: Number, required: true, min: 0, max: 100 },
  },
  { _id: false }
);

const DataQualitySchema = new mongoose.Schema(
  {
    /**
     * true  → stats are based on sufficient data and can be trusted.
     * false → data is sparse; frontend should show a low-data warning.
     */
    sufficient: { type: Boolean, required: true, default: false },

    /** Total number of content items analysed in this window */
    sampleSize: { type: Number, required: true, min: 0 },

    /**
     * Number of calendar days in the window that had at least one
     * piece of content. Low coverage → trend charts are misleading.
     */
    activeDays: { type: Number, required: true, min: 0 },

    /**
     * Ratio of activeDays / windowDays (0–1).
     * Below DATA_QUALITY_THRESHOLDS.MIN_COVERAGE_RATIO → warn.
     */
    coverageRatio: { type: Number, required: true, min: 0, max: 1 },

    /**
     * Human-readable warning message to display when sufficient === false.
     * null when data is sufficient.
     */
    warningMessage: { type: String, default: null },
  },
  { _id: false }
);

// ─── Main schema ──────────────────────────────────────────────────────────────

const moodStatsSchema = new mongoose.Schema(
  {
    // ── Identity ────────────────────────────────────────────────────────────
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      unique: true,   // one live snapshot per user, upserted on recompute
      index: true,
    },

    /** Look-back window (days) used to generate this snapshot */
    windowDays: {
      type: Number,
      required: true,
      min: 1,
      max: 90,
      default: 30,
    },

    /** UTC timestamp when these stats were last computed */
    generatedAt: {
      type: Date,
      required: true,
      default: Date.now,
    },

    // ── Data quality / warnings ──────────────────────────────────────────
    dataQuality: {
      type: DataQualitySchema,
      required: true,
    },

    // ── Summary ─────────────────────────────────────────────────────────
    summary: {
      totalContentAnalyzed:       { type: Number, required: true, min: 0 },
      dominantEmotion:            { type: String, default: null },
      volatility:                 { type: VolatilitySchema, required: true },
      distressDaysCount:          { type: Number, required: true, min: 0 },
      longestConsecutiveDistress: { type: Number, required: true, min: 0 },
    },

    // ── Chart data ───────────────────────────────────────────────────────

    /** Donut chart — 3 slices: positive / negative / neutral */
    polaritySplit: {
      positive: { type: PolarityBucketSchema, required: true },
      negative: { type: PolarityBucketSchema, required: true },
      neutral:  { type: PolarityBucketSchema, required: true },
    },

    /**
     * Horizontal bar chart — sorted descending by count.
     * Top-5 recommended for display; full list stored here.
     * avgScore drives bar colour-intensity / tooltip confidence.
     */
    emotionBreakdown: {
      type: [EmotionBreakdownItemSchema],
      default: [],
    },

    /**
     * Multi-line timeline chart.
     * Each entry = one calendar day with dominant polarity + % breakdown.
     */
    dailyTrend: {
      type: [DailyTrendEntrySchema],
      default: [],
    },

    /** ISO date strings ("YYYY-MM-DD") where negative polarity dominated */
    distressDays: {
      type: [String],
      default: [],
    },

    /** 7-day quick overview card */
    weekSnapshot: {
      type: WeekSnapshotSchema,
      required: true,
    },

    // ── Current aggregation context ─────────────────────────────────────
    /**
     * Mirrors the relevant fields from AggregatedEmotion for convenience
     * (avoids an extra DB lookup on the dashboard API).
     */
    currentAggregation: {
      dominantEmotion: { type: String, default: null },
      topEmotions: {
        type: [
          {
            emotion: { type: String, required: true },
            score:   { type: Number, required: true },
          },
        ],
        default: [],
      },
      llmContext:    { type: String, default: null },
      lastComputedAt:{ type: Date,   default: null },
    },

    // ── Visibility preferences (per-provider, per-seeker) ────────────────
    /**
     * Controls which stat panels are rendered on the dashboard.
     * Defaults to all visible. The provider can toggle individual panels.
     *
     * Keys map to the component/panel identifiers used on the frontend:
     *   emotionBreakdown  → Horizontal Bar Chart
     *   polaritySplit     → Donut Chart
     *   dailyTrend        → Multi-line Timeline
     *   volatility        → Gauge / Speedometer
     *   distressDays      → Calendar Heatmap
     *   consecutiveDistress → Metric Card
     *   weekSnapshot      → 7-Day Card
     */
    selectedStats: {
      emotionBreakdown:   { type: Boolean, default: true },
      polaritySplit:      { type: Boolean, default: true },
      dailyTrend:         { type: Boolean, default: true },
      volatility:         { type: Boolean, default: true },
      distressDays:       { type: Boolean, default: true },
      consecutiveDistress:{ type: Boolean, default: true },
      weekSnapshot:       { type: Boolean, default: true },
    },
  },
  {
    timestamps: true,   // adds createdAt / updatedAt
    versionKey: false,
  }
);

// ─── Indexes ──────────────────────────────────────────────────────────────────

/** Support efficient "fetch latest stats for user" queries */
moodStatsSchema.index({ userId: 1, generatedAt: -1 });

/** Let providers query all seekers with data quality issues */
moodStatsSchema.index({ "dataQuality.sufficient": 1 });

// ─── Statics ──────────────────────────────────────────────────────────────────

/**
 * Upsert a stats snapshot for the given userId.
 * Call this at the end of computeMoodStats() instead of a bare create().
 *
 * @param {string} userId
 * @param {object} statsPayload  — shape matches this schema
 * @returns {Promise<MoodStats>}
 */
moodStatsSchema.statics.upsertForUser = function (userId, statsPayload) {
  return this.findOneAndUpdate(
    { userId },
    { $set: { ...statsPayload, userId } },
    { upsert: true, new: true, runValidators: true }
  );
};

const MoodStats = mongoose.model("MoodStats", moodStatsSchema);
export default MoodStats;